### ISSUE TITLE
Add CommandRunContext.Parameters with plain command line parameters

### ISSUE THREAD

**Issue by valery-vitko** [Steinpilz/confifu-commands#1]
Consider a command producing some text output. It has an optional `path` parameter to redirect output to a file. If the param is omitted, it outputs to `CommandRunContext.Info`. But, in this case `CommandRunContext.Cars["path"]` contains `PATH` environment variable value (strictly speaking, it depends on configured variable chain, but it's the most common case, I assume). Thus, having separate `CommandRunContext.Parameters` collection with access to plain command line parameter values seems to have its benefits.

**Comment by ivanbenko** [comment]
@valery-vitko good point, but I preferred using `IConfigVariables` in `CommandRunContext` because of generic way to pass variables from any source, not only command line arguments, and let the app to decide where to store common variables. I agree that it could be collisions with such general variables names, so I'd suggest the following change: 

All config variables from app's config (not command line arguments) will be prefixed with "Commands:{CommandName}:"

so this 

```
            var taskSpecificVars = new ConfigVariablesBuilder()
                .Add(vars)
                .Add(vars.WithPrefix($"Commands:{def.Name}:"))
                .Build();

```
will become

```
            var taskSpecificVars = vars.WithPrefix($"Commands:{def.Name}:");
```

Variable `path` will be passed to command `Make-Me-Happy` from  *path* command line argument or *Commands:Make-Me-Happy:path* config variable in the app.

**Comment by valery-vitko** [comment]
Agree. Closing the issue then.

**Comment by ivanbenko** [comment]
for reference: it was implemented here https://github.com/Steinpilz/confifu-commands/commit/d169303f855ead8bc504e2d4e0827764f66d69b7 and took effect in version 2.1.0
